[profile.default]
src = "src"
out = "out"
libs = ["lib"]
solc = "0.8.20"
optimizer = true
via_ir = true

remappings = [
    "forge-std/=lib/forge-std/src/",
    "@openzeppelin/contracts=lib/openzeppelin-contracts/contracts",
    "@aerodrome/=lib/contracts/contracts",
    "@chainlink/=lib/foundry-chainlink-toolkit",
    "@contracts/=contracts/",
    "@redstone-finance/evm-connector/dist/contracts/=lib/redstone-oracles-monorepo/packages/evm-connector/contracts/",

]
# See more config options https://github.com/foundry-rs/foundry/blob/master/crates/config/README.md#all-options
